### ISSUE TITLE
Direct float equality check

### ISSUE THREAD

**Issue by fjebaker** [colinsauze/pl_curves#3]
Don't direct float equality check!

https://github.com/colinsauze/pl_curves/blob/d7a1a65d2f8a61305a73ede4c5a3432ea82eb32c/tests/test_run.py#L34-L37

Use `pytest.approx`.

**Comment by fjebaker** [comment]
https://github.com/colinsauze/pl_curves/blob/d7a1a65d2f8a61305a73ede4c5a3432ea82eb32c/tests/test_calculate_cumulative_relative_abundance.py#L34-L38

**Comment by fjebaker** [comment]
Also in `test_gini.py` and `test_make_gini_file.py`.

**Comment by colinsauze** [comment]
Now fixed
